Feat/auth v2
stepanchaban/rick-morty-team pull request #12
Opened 2024-02-10 13:33 UTC by stepanchaban

2024-02-11 09:57 UTC, AlinaLaniuk requested changes
прошу внести изменения по двум комментариям (относительно пути и стора)

2024-02-11 09:57 UTC, AlinaLaniuk commented on src/components/App/Header/Header.tsx
> +import logo from '../../../sources/icons/logo.png';
затерты изменения из мейна. пути должны быть прописаны через алиас.
прошу исправить.

2024-02-11 09:57 UTC, AlinaLaniuk commented on src/components/App/common/Form.tsx
> +}: FormProps): ReactElement => {
https://github.com/stepanchaban/rick-morty-team/pull/5#discussion_r1482651220

тут ничего не изменилось, кроме того, что теперь пропсов стало еще больше) а надо было наоборот сократить их количество.

2024-02-11 09:57 UTC, AlinaLaniuk commented on src/components/App/common/Form.tsx
> +
мне кажется логичнее здесь использовать тип, а не интерфейс, так как пропсы не будут изменяться.

2024-02-11 09:57 UTC, AlinaLaniuk commented on src/components/App/common/Form.tsx
> +        <label>
а зачем тут проверка и на флаг, и на showConfirmPasswordInput?

2024-02-11 09:57 UTC, AlinaLaniuk commented on src/pages/signin/Signin.tsx
> +    const formData = new FormData(event.currentTarget);
зачем здесь используется FormData? форма же не отправляется никуда

2024-02-11 09:57 UTC, AlinaLaniuk commented on src/pages/signin/Signin.tsx
> +    event: React.FormEvent<HTMLFormElement>,
почему эта функция асинхронная? здесь же вообще нет никакой асинхронщины

2024-02-11 09:57 UTC, AlinaLaniuk commented on src/store/store.ts
> +
что все это делает в сторе? это должно быть в отдельном файле.
прошу исправить

2024-02-11 11:08 UTC, RitaLitvin commented on src/store/store.ts
> +
да, по-хорошему слайсы должны быть написаны в отдельных файлах и лежать в папках с соответствующими фичами. но у Степы три компонента (header, signin, signup) используют этот слайс. вопрос: куда его положить? либо делать общий компонент, либо давайте хранить всю редакс логику в отдельной папке.  Например, в папке src создадим папку redux, там будет файл store и папка slices

2024-02-11 12:34 UTC, RitaLitvin requested changes
нужно вынести слайс из файла store в отдельный файл. предлагаю так: в папке src создать папку redux, там будет файл store и папка slices

2024-02-11 12:34 UTC, RitaLitvin commented on src/components/App/common/Form.tsx
> +export default Form;
почему форма лежит в папке common?) почему не просто в папке Form? просто спрашиваю

2024-02-11 12:51 UTC, stepanchaban commented on src/components/App/common/Form.tsx
> +        <label>
забыл убрать, когда рефакторил

2024-02-11 14:32 UTC, AlinaLaniuk approved these changes
многие комменты из https://github.com/stepanchaban/rick-morty-team/pull/5 все еще актуальны. в будущем стоит уделить время рефакторингу.
функционал рабочий. как обсуждалось, ставлю апрув.

2024-02-11 14:37 UTC, RitaLitvin approved these changes

2024-02-12 05:48 UTC, stepanchaban commented on src/components/App/common/Form.tsx
> +export default Form;
в папке common можно будет класть ui

2024-02-12 06:59 UTC, steeksg requested changes

2024-02-12 06:59 UTC, steeksg commented on src/components/App/common/Form.tsx
> +
Это холиваная история) По сути большой разници нет в 99.999999% случаев. я бы рекомендовал всегда использовать типы и не париться. Т.е. отличие между интерфейсом и типом есть, но в практическом использовании для нас нет большой разницы

2024-02-12 06:59 UTC, steeksg commented on src/pages/signup/Signup.tsx
> +const validatePassword = (password: string): string =>
В этих двух формах много коиппастного кода. Выдели в утилсы и константы то что повторяется. Сделай более универсальным.

2024-02-12 12:42 UTC, merged